apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-09-29T02:12:53Z"
  labels:
    app: db-pod
  name: db-pod
spec:
  selector:
    app: db-pod
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-09-29T02:12:53Z"
  labels:
    app: db-pod
  name: db-pod
  namespace: hardhat
spec:
  containers:
  - args:
    - postgres
    - -D
    - /etc/postgresql
    envFrom:
      - secretRef:
          name: db-env
    image: docker.io/supabase/postgres:17.6.1.011
    name: supabase-postgres
    ports:
      - containerPort: 5432
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: pgdata-pvc
  livenessProbe:
    exec:
      command:
        - pg_isready
        - -U
        - admin
        - -d
        - postgres
    initialDelaySeconds: 5
    periodSeconds: 1
    timeoutSeconds: 5
    failureThreshold: 10
  volumes:
  - name: pgdata-pvc
    persistentVolumeClaim:
      claimName: pgdata
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-09-29T02:12:53Z"
  labels:
    app: scraper-pod
  name: scraper-pod
  namespace: hardhat
spec:
  selector:
    app: scraper-pod
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Pod
metadata:
  namespace: hardhat
  name: scraper-pod
spec:
  containers:
    - name: scraper-dev
      image: localhost/hardhat-scraper-dev:latest
      envFrom:
        - secretRef:
            name: scraper-env
      volumeMounts:
        - name: scraper-src
          mountPath: /app
          readOnly: false
      ports:
        - containerPort: 8000
          hostPort: 8000
  networks:
    - name: hardhat-net
  volumes:
    - name: scraper-src
      hostPath:
        path: ./scraper/src/
        type: Directory