FROM python:3.13.7-alpine3.22 AS builder

ENV PYTHONUNBUFFERED=1

RUN apk add --no-cache \
    gcc \
    musl-dev \
    python3-dev \
    postgresql-dev \
    libffi-dev \
    openssl-dev \
    build-base

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

FROM python:3.13.7-alpine3.22

ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apk add --no-cache \
    postgresql-libs \
    libffi \
    openssl

COPY --from=builder /install /usr/local

COPY ./src /app

ENTRYPOINT ["ash", "entrypoint.sh"]